# Generated by Django 4.2.1 on 2023-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_contacts_email_alter_contacts_inst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whats',
            field=models.CharField(max_length=12),
        ),
    ]
